apiVersion: v1
kind: Service
metadata:
    name: redis-master
    labels:
        type: back-end-service
spec:
    selector:
        app: back-end
    ports:
        - port: 6379
          targetPort: 6379


