apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: front-end-deploy
    labels:
        app: front-end
spec:
    selector:
        matchLabels:
            app: front-end
    template:
        metadata:
            name: guestbook
            labels:
                app: front-end  
        spec:
            containers:
                - name: guestbook
                  image: kubernetes/guestbook:v2
                  ports:
                    - containerPort: 3000
    replicas: 1

